import type { NotebookExport, NotebookCell } from '@/types'
import type { Quest } from '@/types'

// ─────────────────────────────────────────────────────────────
// Generates a Jupyter-compatible .ipynb notebook from a
// completed quest — ready to push to GitHub for submission.
// ─────────────────────────────────────────────────────────────

interface QueryEntry {
  floorTitle: string
  query:      string
  result:     string   // stringified result table
}

export function buildNotebook(quest: Quest, queries: QueryEntry[]): object {
  const queriesByFloor = new Map(queries.map(entry => [entry.floorTitle, entry]))
  const cells: object[] = []

  cells.push(markdownCell([
    `# SQL:DUNGEON — ${quest.title}`,
    ``,
    `**Quest ID:** ${quest.id}  `,
    `**Rank:** ${quest.rank}  `,
    `**Exported:** ${new Date().toLocaleString()}`,
    ``,
    `---`,
    ``,
    `## Lore`,
    ``,
    `*${quest.lore}*`,
  ]))

  cells.push(markdownCell([
    `## Notebook Notes`,
    ``,
    `Use this notebook to capture your reasoning, query evolution, and what each result changed in your thinking.`,
    ``,
    `- Record what business or mystery question each part is answering.`,
    `- Keep the SQL you tested, even when it was not your final approach.`,
    `- End with a plain-language recommendation or verdict that matches the quest answer format.`,
    ``,
    `**Final answer hint:** ${quest.answerHint}`,
  ]))

  const schemaLines = [`## Database Schema`, ``]
  Object.entries(quest.schema).forEach(([table, cols]) => {
    schemaLines.push(`### \`${table}\``)
    schemaLines.push(`| Column | Type | PK |`)
    schemaLines.push(`|--------|------|----|`)
    cols.forEach(c => schemaLines.push(`| ${c.col} | ${c.type} | ${c.pk ? '✓' : ''} |`))
    schemaLines.push(``)
  })
  cells.push(markdownCell(schemaLines))

  quest.floors.forEach((floor, index) => {
    const savedEntry = queriesByFloor.get(floor.title)
    cells.push(markdownCell([
      `## ${floor.title}`,
      ``,
      `**Objective:** ${floor.intro}`,
      ``,
      `**What to note here**`,
      ``,
      `- What signal or comparison are you trying to surface?`,
      `- Which tables or columns mattered most?`,
      `- What did the result rule in or rule out?`,
    ]))
    cells.push(codeCell(
      savedEntry?.query ??
        `-- ${floor.title}\n-- Objective: ${floor.intro}\n-- Notes: ${floor.hint}\n\n-- Write your T-SQL here`,
      savedEntry?.result ?? '',
      index
    ))
    cells.push(markdownCell([
      `### Reflection`,
      ``,
      `- What did this part teach you?`,
      `- What will you test next?`,
    ]))
  })

  cells.push(markdownCell([
    `## Verdict`,
    ``,
    `Write the final answer here in the format the quest expects: **${quest.answerHint}**`,
    ``,
    `Add a short explanation of why the evidence supports that answer.`,
    ``,
    `---`,
    `*Generated by SQL:DUNGEON · CSCI 331 · Queens College CUNY*`,
  ]))

  return {
    nbformat:       4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: {
        display_name: 'SQL',
        language:     'sql',
        name:         'sql',
      },
      language_info: { name: 'sql' },
      sqldungeon: {
        quest_id:    quest.id,
        quest_title: quest.title,
        exported_at: new Date().toISOString(),
      },
    },
    cells,
  }
}

function markdownCell(lines: string[]): object {
  return {
    cell_type: 'markdown',
    id:        crypto.randomUUID().slice(0, 8),
    metadata:  {},
    source:    lines.join('\n'),
  }
}

function codeCell(query: string, output: string, idx: number): object {
  return {
    cell_type:        'code',
    id:               crypto.randomUUID().slice(0, 8),
    metadata:         {},
    execution_count:  idx + 1,
    source:           query,
    outputs: output ? [
      {
        output_type: 'stream',
        name:        'stdout',
        text:        output,
      }
    ] : [],
  }
}

// Also export as plain .sql file (simpler, always works)
export function buildSQLFile(quest: Quest, queries: QueryEntry[]): string {
  const lines: string[] = [
    `-- ═══════════════════════════════════════════════════════`,
    `-- SQL:DUNGEON — ${quest.title}`,
    `-- Quest: ${quest.id} · Rank: ${quest.rank}`,
    `-- Exported: ${new Date().toLocaleString()}`,
    `-- CSCI 331 · Queens College CUNY`,
    `-- ═══════════════════════════════════════════════════════`,
    ``,
  ]

  queries.forEach(entry => {
    lines.push(`-- ── ${entry.floorTitle} ─────────────────────────────────────`)
    lines.push(entry.query)
    if (entry.result) {
      lines.push(``)
      lines.push(`/* Results:`)
      lines.push(entry.result)
      lines.push(`*/`)
    }
    lines.push(``)
  })

  return lines.join('\n')
}
