import type { NotebookExport, NotebookCell } from '@/types'
import type { Quest } from '@/types'

// ─────────────────────────────────────────────────────────────
// Generates a Jupyter-compatible .ipynb notebook from a
// completed quest — ready to push to GitHub for submission.
// ─────────────────────────────────────────────────────────────

interface QueryEntry {
  floorTitle: string
  query:      string
  result:     string   // stringified result table
}

export function buildNotebook(quest: Quest, queries: QueryEntry[]): object {
  const cells: object[] = []

  // Title cell
  cells.push(markdownCell([
    `# SQL:DUNGEON — ${quest.title}`,
    ``,
    `**Quest ID:** ${quest.id}  `,
    `**Rank:** ${quest.rank}  `,
    `**Exported:** ${new Date().toLocaleString()}`,
    ``,
    `---`,
    ``,
    `## Lore`,
    ``,
    `*${quest.lore}*`,
  ]))

  // Schema cell
  const schemaLines = [`## Database Schema`, ``]
  Object.entries(quest.schema).forEach(([table, cols]) => {
    schemaLines.push(`### \`${table}\``)
    schemaLines.push(`| Column | Type | PK |`)
    schemaLines.push(`|--------|------|----|`)
    cols.forEach(c => schemaLines.push(`| ${c.col} | ${c.type} | ${c.pk ? '✓' : ''} |`))
    schemaLines.push(``)
  })
  cells.push(markdownCell(schemaLines))

  // Part cells
  queries.forEach((entry, i) => {
    cells.push(markdownCell([`## ${entry.floorTitle}`]))
    cells.push(codeCell(entry.query, entry.result, i))
  })

  // Conclusion cell
  cells.push(markdownCell([
    `## Verdict`,
    ``,
    `Quest completed. All four parts cleared.`,
    ``,
    `---`,
    `*Generated by SQL:DUNGEON · CSCI 331 · Queens College CUNY*`,
  ]))

  return {
    nbformat:       4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: {
        display_name: 'SQL',
        language:     'sql',
        name:         'sql',
      },
      language_info: { name: 'sql' },
      sqldungeon: {
        quest_id:    quest.id,
        quest_title: quest.title,
        exported_at: new Date().toISOString(),
      },
    },
    cells,
  }
}

function markdownCell(lines: string[]): object {
  return {
    cell_type: 'markdown',
    id:        crypto.randomUUID().slice(0, 8),
    metadata:  {},
    source:    lines.join('\n'),
  }
}

function codeCell(query: string, output: string, idx: number): object {
  return {
    cell_type:        'code',
    id:               crypto.randomUUID().slice(0, 8),
    metadata:         {},
    execution_count:  idx + 1,
    source:           query,
    outputs: output ? [
      {
        output_type: 'stream',
        name:        'stdout',
        text:        output,
      }
    ] : [],
  }
}

// Also export as plain .sql file (simpler, always works)
export function buildSQLFile(quest: Quest, queries: QueryEntry[]): string {
  const lines: string[] = [
    `-- ═══════════════════════════════════════════════════════`,
    `-- SQL:DUNGEON — ${quest.title}`,
    `-- Quest: ${quest.id} · Rank: ${quest.rank}`,
    `-- Exported: ${new Date().toLocaleString()}`,
    `-- CSCI 331 · Queens College CUNY`,
    `-- ═══════════════════════════════════════════════════════`,
    ``,
  ]

  queries.forEach(entry => {
    lines.push(`-- ── ${entry.floorTitle} ─────────────────────────────────────`)
    lines.push(entry.query)
    if (entry.result) {
      lines.push(``)
      lines.push(`/* Results:`)
      lines.push(entry.result)
      lines.push(`*/`)
    }
    lines.push(``)
  })

  return lines.join('\n')
}
